version: '3'

services:
  api:
    build: ./api
    ports:
      - "127.0.0.1:3001:3001"
    x-develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  app:
    build: ./ui
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./ui:/app/ui
      - ignore:/app/ui/node_modules/

volumes:
  ignore:
